# Generated by Django 3.2.4 on 2021-06-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('pk',), 'verbose_name': ('Пользователь',), 'verbose_name_plural': ('Пользователи',)},
        ),
    ]
