# Generated by Django 3.2.3 on 2021-06-06 09:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_alter_recipeingredient_recipe'),
        ('api', '0003_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('author', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('recipe', 'user')},
        ),
    ]
