# Generated by Django 3.2.3 on 2021-06-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipeingredient_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit',
            new_name='dimension',
        ),
    ]
