# Generated by Django 3.2.3 on 2021-06-09 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename_unit_ingredient_dimension'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('ingredient', 'recipe')},
        ),
    ]
