# Generated by Django 3.2.3 on 2021-06-09 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipeingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество'),
        ),
    ]
